# syntax=docker/dockerfile:1.6

# https://askubuntu.com/questions/972516/debian-frontend-environment-variable
ARG DEBIAN_FRONTEND=noninteractive

# Globally set pip break-system-packages option to avoid having to specify it every time
ARG PIP_BREAK_SYSTEM_PACKAGES=1


FROM deps AS ax-frigate
ARG TARGETARCH
ARG PIP_BREAK_SYSTEM_PACKAGES

WORKDIR /opt/frigate/
COPY --from=rootfs / /

# Install axmodels
COPY docker/axera/axmodels /axmodels

# Install axpyengine
COPY docker/axera/pyaxengine/axengine-0.1.3-py3-none-any.whl /axengine-0.1.3-py3-none-any.whl
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ /axengine-0.1.3-py3-none-any.whl \
    && rm /axengine-0.1.3-py3-none-any.whl

# Install axera ffmpeg
RUN --mount=type=bind,source=docker/axera/install_ax_ffmpeg.sh,target=/deps/install_ax_ffmpeg.sh \
    /deps/install_ax_ffmpeg.sh

# Set ldconfig path
RUN echo "/soc/lib" > /etc/ld.so.conf.d/ax.conf

# Make sure only Python 3.11 is installed.
RUN apt-get purge -y python3.10 python3.10-minimal \
    && apt-get autoremove -y \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 \
    && update-alternatives --set python3 /usr/bin/python3.11 \
    && python3 --version

# Set ffmpeg version
ENV DEFAULT_FFMPEG_VERSION="ax"
ENV INCLUDED_FFMPEG_VERSIONS="${DEFAULT_FFMPEG_VERSION}:${INCLUDED_FFMPEG_VERSIONS}"
